<a href="https://colab.research.google.com/github/CindyZambrano/CindyZambrano/blob/main/tareaNumpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

print(np.__version__)

1.22.4


In [ ]:
import numpy as np

arr = np.array(range(10))
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
import numpy as np

arr = np.ones((3, 3), dtype=bool)
print(arr)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

odd_numbers = arr[arr % 2 != 0]
print(odd_numbers)

[1 3 5 7 9]


In [ ]:
import numpy as np

arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

arr[arr % 2 != 0] = -1
print(arr)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [ ]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6])

arr_2d = np.reshape(arr_1d, (2, -1))
print(arr_2d)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.vstack((a, b))
print(result)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.hstack((a, b))
print(result)

[1 2 3 4 5 6]


In [ ]:
import numpy as np

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

items_between_5_and_10 = a[(a >= 5) & (a <= 10)]
print(items_between_5_and_10)

[ 5  6  7  8  9 10]


In [ ]:
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(7):
  tmp.append(maxx(a[i],b[i]))
print(tmp)

[6, 7, 9, 8, 9, 7, 5]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)

[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [ ]:
import numpy as np

lower_bound = 0.0
upper_bound = 1.0

arr = np.random.uniform(lower_bound, upper_bound, size=(5, 3))
print(arr)

[[0.06715836 0.39535346 0.58287108]
 [0.08537863 0.8089118  0.06022667]
 [0.42703047 0.63572034 0.90035512]
 [0.97206379 0.8842068  0.36803042]
 [0.22648821 0.24272745 0.23042836]]
